name: clustergram
channels:
  - conda-forge
dependencies:
  - scikit-learn
  - pandas
  - numpy
  - bokeh
  - contextily  # for urbangrammar-graphics
  - pip
  - pip:
    - urbangrammar-graphics
    - git+https://github.com/martinfleis/clustergram.git
    - seaborn