name: clustergram
channels:
  - conda-forge
dependencies:
  - scikit-learn
  - scipy
  - seaborn
  - pandas
  - matplotlib
  - bokeh
  - pip:
      - git+https://github.com/martinfleis/clustergram.git